# Generated by Django 5.0.7 on 2024-08-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
