# Generated by Django 5.0.7 on 2024-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
