# Generated by Django 5.0.7 on 2024-09-16 19:10

import pdf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_book_isbn13_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='noavatar.png', null=True, upload_to=pdf.models.filename, verbose_name='Image'),
        ),
    ]
